<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LP-13" name="UniqueCouponMultipleTime_SNo_39" tests="1" failures="1" timestamp="11 Aug 2015 05:02:49 GMT" time="68.583" errors="0">
  <testcase name="executeTestCase" time="32.013" classname="BugRegressionSuite.UniqueCouponMultipleTime_SNo_39">
    <failure type="java.lang.AssertionError" message="expected [Sorry, This coupon code is not valid] but found [Have other coupon? Reapply to avail the offer]">
      <![CDATA[java.lang.AssertionError: expected [Sorry, This coupon code is not valid] but found [Have other coupon? Reapply to avail the offer]
	at BugRegressionSuite.UniqueCouponMultipleTime_SNo_39.executeTestCase(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- executeTestCase -->
</testsuite> <!-- UniqueCouponMultipleTime_SNo_39 -->
